### ISSUE TITLE
'onTouchMove' listener is causing issues after removing all listeners

### ISSUE THREAD

**Issue by davidalee** [BoxFactura/pulltorefresh.js#18] opened 2017-04-04 20:18 UTC
I'm experiencing an issue when I toggle between two pages in my app. The first page has the pull to refresh feature, the second page does not have this feature so when the user navigates to the second page, I invoke the destroy method to remove the listeners. But when I scroll on the second page, I get an error 

```TypeError: Cannot read property 'classList' of undefined at _onTouchMove```

and all of my content disappears.

**Comment by faelsoto** [comment] 2017-04-05 01:49
It would help wonders if you could create a demo with this issue, so we can reproduce and fix the problem.

**Comment by davidalee** [comment] 2017-04-05 02:43
Apologies, I started working on a plunker for this but couldn't finish it due to work stuff. Essentially a "ontouchmove" event exists on the window even after the destroy method has been invoked (use the getEventListeners() method in chrome devtools console after invoking destroy()).

**Comment by davidalee** [comment] 2017-04-05 17:20
I'm trying to create a plnkr to reproduce this issue, but I'm having issues importing the script for some reason.

In order to reproduce this error, open up any app using this library in Chrome and invoke `destroy()` after initializing the library. Use `getEventListeners(window)` and you'll see that there still exists an event listener for the `touchmove` event although the other two event listeners that are initialized have been removed.

If you re-initialize the library at this point and check the event listeners, you'll see that the other two touch events have been added but now there are two `touchmove` listeners whereas there should be just one, the one that was just added as well as the listener that was not removed from the first initialization.

If you remove the `{ passive: false }` on line 298 (when the event listener is removed) and try running through the same steps listed above, all events including `touchmove` are removed properly after invoking `destroy()`.

**Comment by davidalee** [comment] 2017-04-05 18:03
It seems there is already a PR that addresses this issue:

https://github.com/BoxFactura/pulltorefresh.js/pull/15

**Comment by UziTech** [comment] 2017-04-05 20:22
does it work to add `{ passive: false }` to the `removeEventListener` call on line [#284](https://github.com/BoxFactura/pulltorefresh.js/blob/master/src/pulltorefresh.js#L284)

Like this:

```javascript
window.removeEventListener('touchmove', handlers.onTouchMove, { passive: false });
```

**Comment by UziTech** [comment] 2017-04-06 02:06
@davidalee I tried to reproduce this but `destroy` worked to remove the `touchmove` event for me.

What version of chrome are you using?

```
Chrome Version 58.0.3029.41 (Official Build) beta (64-bit)
Windows 10
```
![image](https://cloud.githubusercontent.com/assets/97994/24734439/fc71b582-1a42-11e7-9415-21fa044a77fd.png)

**Comment by pateketrueke** [comment] 2017-06-26 00:55
Hi guys, closing this since I've merged the pending PRs. 👍

**Closed by pateketrueke** 2017-06-26 00:55 UTC
