### ISSUE TITLE
Cannot read property 'classList' of null 

### ISSUE THREAD

**Issue by pengfu** [BoxFactura/pulltorefresh.js#32] opened 2018-03-26 14:54 UTC
When quickly slide the page, it may come across 
Cannot read property 'classList' of null   or
Cannot read property 'style' of null 
![image](https://user-images.githubusercontent.com/7261281/37913745-3141fbce-3148-11e8-829e-1fc5923c251d.png)

I think the reason is the `onReset` function
handler.ptrElement = null;
handler.ptrElement is set to null ,but it is referenced in touchmove callback however.

**Comment by pateketrueke** [comment] 2018-03-26 15:07
Hi, nice bug tbh... 💣 

We'll work on this asap, thanks for your feedback!

**Comment by crusy** [comment] 2018-04-16 07:40
I have the same problem here. Explicitly setting ptrElement helps avoiding this error, but I get an

> Uncaught TypeError: Cannot set property 'innerHTML' of null
    at Object.update (pulltorefresh.js:125)

instead, at _onTouchStart (pulltorefresh.js:160), _onTouchMove (pulltorefresh.js:188), _onTouchMove (pulltorefresh.js:206), _onTouchEnd (pulltorefresh.js:249).

**Comment by Anduin2017** [comment] 2018-04-16 08:51
The same problem here!

**Comment by pateketrueke** [comment] 2018-05-09 15:29
Hi @NightCatSama which version you're using of?

I encourage you to use `0.1.12` because it's the latest version and should be fixed now, if not is your case, please reopen this issue.

Thank you!

**Comment by NightCatSama** [comment] 2018-05-09 15:50
@pateketrueke The version I use is `0.1.13`.

I also have this problem in the documentation example. After the refresh is complete, the drop-down will report an error.


![image](http://7xqnme.com1.z0.glb.clouddn.com/18-5-9/71124335.jpg)

**Comment by pateketrueke** [comment] 2018-05-09 15:57
Oh, I see... I'm not able to reproduce that.

I hope this is not a caching issue.

Can you guide me through out?

**Comment by NightCatSama** [comment] 2018-05-09 16:01
of course.

First trigger the refresh pop-up alert, and then click OK to return to the page and pull down again (in the moment of closing completion).

**Comment by NightCatSama** [comment] 2018-05-09 16:48
You're welcome, thanks to open source for such a great library.

**Comment by pateketrueke** [comment] 2018-05-10 05:11
I just released  `0.1.14`, the issue was that I released the same version twice without any rebuild... _mea culpa_.

**Comment by NightCatSama** [comment] 2018-05-10 06:36
Solved, thank you. 😄

**Closed** 2018-05-10 13:27 UTC
